
title: Jonas Vonäsch ETHZ
description: 

theme: minima

defaults:
  - scope:
      path: ""
      #type: "pages"
    values:
      nav: main
      layout: page
  - scope:
      path: "teaching"
    values:
      nav: teaching

plugins:
  - jekyll-feed
  - jekyll-seo-tag
