
title: Jonas Vonäsch
description: 

theme: minima

defaults:
  - scope:
      path: ""
    values:
      pagebar: main
      layout: page
  - scope:
      path: "teaching"
    values:
      pagebar: teaching
      category_title: "Teaching Material"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
